######################################################################
# Automatically generated by qmake (3.0) mié jul 9 13:39:15 2014
######################################################################

QT = core gui widgets
QT += sql
TEMPLATE = app
TARGET = ICTUMTest
INCLUDEPATH += . headers

# Input
HEADERS += headers/actor.h \
           headers/actor_add_edit_dialog.h \
           headers/actor_function_matrix.h \
           headers/actor_ou_matrix.h \
           headers/actor_process_matrix.h \
           headers/actor_role_matrix.h \
           headers/add_iss_helper_dialog.h \
           headers/add_physical_component_helper_dialog.h \
           headers/add_processes_helper_dialog.h \
           headers/add_roles_helper_dialog.h \
           headers/artifacts.h \
           headers/checkbox_delegate.h \
           headers/data_entity.h \
           headers/data_entity_add_edit_dialog.h \
           headers/data_entity_info_system_matrix.h \
           headers/data_entity_navigation.h \
           headers/data_entity_roles_matrix.h \
           headers/data_handler.h \
           headers/function.h \
           headers/function_add_edit_dialog.h \
           headers/info_system_service_support_matrix.h \
           headers/info_system_services_dependency_matrix.h \
           headers/info_system_services_roles_matrix.h \
           headers/information_system_service.h \
           headers/information_system_service_add_edit_dialog.h \
           headers/location.h \
           headers/location_add_edit_dialog.h \
           headers/mainwindow.h \
           headers/navigation.h \
           headers/organizational_unit.h \
           headers/ou_add_edit_dialog.h \
           headers/ou_function_matrix.h \
           headers/ou_navigation.h \
           headers/physical_component_roles_matrix.h \
           headers/physical_component_support_matrix.h \
           headers/physical_tech_component_location_matrix.h \
           headers/physical_tech_component_navigation.h \
           headers/physical_technology_component.h \
           headers/physical_technology_component_add_edit_dialog.h \
           headers/process.h \
           headers/process_add_edit_dialog.h \
           headers/role.h \
           headers/role_add_edit_dialog.h \
           headers/role_function_matrix.h \
           headers/role_process_matrix.h \
           headers/roles_navigation.h
SOURCES += main.cpp \
           sources/actor.cpp \
           sources/actor_add_edit_dialog.cpp \
           sources/actor_funcion_matrix.cpp \
           sources/actor_ou_matrix.cpp \
           sources/actor_process_matrix.cpp \
           sources/actor_role_matrix.cpp \
           sources/add_iss_helper_dialog.cpp \
           sources/add_physical_component_helper_dialog.cpp \
           sources/add_processes_helper_dialog.cpp \
           sources/add_roles_helper_dialog.cpp \
           sources/artifacts.cpp \
           sources/checkbox_delegate.cpp \
           sources/data_entity.cpp \
           sources/data_entity_add_edit_dialog.cpp \
           sources/data_entity_info_system_matrix.cpp \
           sources/data_entity_navigation.cpp \
           sources/data_entity_roles_matrix.cpp \
           sources/data_handler.cpp \
           sources/function.cpp \
           sources/function_add_edit_dialog.cpp \
           sources/info_system_service_support_matrix.cpp \
           sources/info_system_services_dependency_matrix.cpp \
           sources/info_system_services_roles_matrix.cpp \
           sources/information_system_service.cpp \
           sources/information_system_service_add_edit_dialog.cpp \
           sources/location.cpp \
           sources/location_add_edit_dialog.cpp \
           sources/mainwindow.cpp \
           sources/navigation.cpp \
           sources/organizational_unit.cpp \
           sources/ou_add_edit_dialog.cpp \
           sources/ou_function_matrix.cpp \
           sources/ou_navigation.cpp \
           sources/physical_component_roles_matrix.cpp \
           sources/physical_component_support_matrix.cpp \
           sources/physical_tech_component_location_matrix.cpp \
           sources/physical_tech_component_navigation.cpp \
           sources/physical_technology_component.cpp \
           sources/physical_technology_component_add_edit_dialog.cpp \
           sources/process.cpp \
           sources/process_add_edit_dialog.cpp \
           sources/role.cpp \
           sources/role_add_edit_dialog.cpp \
           sources/role_function_matrix.cpp \
           sources/role_process_matrix.cpp \
           sources/roles_navigation.cpp
